version: '3.8'

services:
  user-service:
    build:
      context: ./UserService/Backend  
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 
    networks:
      - backend

  product-service:
    build:
      context: ./ProductService/Backend 
      dockerfile: Dockerfile
    ports:
      - "8002:8002"  
    networks:
      - backend

  order-service:
    build:
      context: ./OrderService/Backend  
      dockerfile: Dockerfile
    ports:
      - "8001:8001"  
    networks:
      - backend

  graphql-service:
    build:
      context: ./graphql-gateway  
      dockerfile: Dockerfile

    ports:
      - "7000:7000"  
    environment:
      USER_SERVICE_URL: "http://user-service:8000" 
      PRODUCT_SERVICE_URL: "http://product-service:8002"
      ORDER_SERVICE_URL: "http://order-service:8001"
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - backend

networks:
  backend:
    driver: bridge
